### PR TITLE
Fix hues for Bags of Sending

### PR DESCRIPTION
**Pull request by blendax78**
You couldn't actually set the hue (randomly/automatically or manually) on item creation.

### CODE REVIEW

**Comment by kamronbatman** [comment]
What happens when you try to do something like:

`[add bagofsending yellow`

Or without the argument?

**Comment by blendax78** [comment]
Without fix:
image
Commands:
`[add bagofholding`
`[add bagofholding`
`[add bagofholding`
`[add bagofholding yellow`
`[add bagofholding blue`
`[add bagofholding red`

**Comment by blendax78** [comment]
With fix:
image
Commands:
[add bagofholding
[add bagofholding
[add bagofholding
[add bagofholding yellow
[add bagofholding blue
[add bagofholding red

**Comment by blendax78** [comment]
oops .. meant to say `[add bagofsending` NOT `[add bagofholding` 😆

**Pull request merged**
