### PR TITLE
* Exceptional chance was always showing 55%

### PR DESCRIPTION
**Pull request by mark1145**

### CODE REVIEW

**Comment by mark1145** [comment]
Hi @kamronbatman,

I found a minor bug, essentially the craft chance was always being set to 1 and so when the CraftItem.GetExceptionalChance() went to calculate exceptional chance, it would always be 1 - 0.45

**Comment by kamronbatman** [comment]
@mark1145 I made a change. Let me know if this works too!

**Comment by mark1145** [comment]
Hi @kamronbatman,

It looks good, I'm not sure why that if statement was there, I had thought maybe there was a narrow scenario when the person has exactly enough skill + uses a talisman but I can't see it does anything

**Comment by kamronbatman** [comment]
> Hi @kamronbatman,
> 
> It looks good, I'm not sure why that if statement was there, I had thought maybe there was a narrow scenario when the person has exactly enough skill + uses a talisman but I can't see it does anything

Left over from long ago... Who knows 😀

**Pull request merged**
